#!/bin/sh
# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

# gamerlay-review - Automates the Gentoo GamerLay Overlay commit process
# Released into the public domain.

. /etc/init.d/functions.sh

tmpdir="/tmp/$(basename ${0}).$$"
patchset=${tmpdir}/gamerlay-patchset.patch
review_msg="Reviewed up $(date "+%Y/%m/%d %H:%M")"
have_binaries=""
exclude_list=""

die() {
    eerror $1
    exit 1
}


test -d ${tmpdir} || mkdir ${tmpdir}
git diff --patch-with-stat --full-index master > ${patchset} \
    || die "Diff between devel and stable branches failed"

git checkout master || die "Switch to stable branch failed"
# Why --exclude=Documentation/ or --exclude=scripts/ doesn't work ?
# WTF ?
git apply --whitespace=nowarn ${exclude_list} ${patchset} \
    || die "Unable to apply patchset"
#FIXME: Use --exclude option, when an alternative would be found
rm -rf Documentation/ scripts/
repoman commit -m ${review_msg}
einfo "${review_msg}...commited"
rm -rf ${tmpdir}
